### ISSUE TITLE
自荐我的 GitHub 插件

### ISSUE THREAD

**Issue by EnixCoda** [zhaoolee/ChromeAppHeroes#11]
[GitHub Repository](https://github.com/EnixCoda/Gitako/)

[Chrome Web Store](https://chrome.google.com/webstore/detail/gitako/giljefjcheohhamkjphiebfjnlphnokk)

功能上类似于大名鼎鼎的 Octotree ，但是用了更现代化的前端工具，性能好很多。

希望您喜欢，

多谢！

**Comment by zhaoolee** [comment]
感谢贡献, 已收录~

> ![](https://upload-images.jianshu.io/upload_images/3203841-d7a6cfbe5e4bc722.png)
