### ISSUE TITLE
自荐我的 Chrome 插件，大概有 4000+ 的用户使用

### ISSUE THREAD

**Issue by zhuowenli** [zhaoolee/ChromeAppHeroes#13]
插件名:  GITHUBER

简介:  :octocat: 这是一个帮助 GitHub 开发者每日发现优质内容的 Chrome 主页拓展。

Github 地址:  https://github.com/zhuowenli/githuber

Chrome 扩展商店地址: https://chrome.google.com/webstore/detail/githuber/janmcneaglgklfljjcpihkkomeghljnf

**Comment by zhaoolee** [comment]
已收录,感谢您对 谷粒-Chrome插件英雄榜 的贡献~
