### ISSUE TITLE
希望可以纠正「扩展」与「插件」的区别

### ISSUE THREAD

**Issue by hjthjthjt** [zhaoolee/ChromeAppHeroes#14]
在 chrome 中，插件和扩展是两个截然不同的概念，插件指 chrome://plugin(新版本移除了，chrome://components可以看出一点痕迹)，而这个repo严格来说介绍的是chrome扩展程序（extension），也就是chrome://extensions中的东西。
希望可以在readme中正确介绍为扩展/extension，而不是用插件/plugin的说法。

**Comment by zhaoolee** [comment]
或许将这个仓库命名为**Chrome扩展英雄榜**更准确些,但**插件**这个名词, 更通俗易懂, 所以就使用了**Chrome插件英雄榜**这个命名

以上内容已添加到README, 感谢您对 谷粒-Chrome插件英雄榜的贡献!
