### ISSUE TITLE
gitbooks图片无法显示

### ISSUE THREAD

**Issue by zhuxiaodongwx** [zhaoolee/ChromeAppHeroes#15]
gitbooks的图片无法从简书加载，403错误
所有插件介绍的图片均失效，gitebooks已无法使用。

故障页面举例：
https://zhaoolee.gitbooks.io/chrome/content/001-markdownyi-jian-zhuan-huan-523022-fu-wen-ben-ge-5f0f22.html

**Comment by zhaoolee** [comment]
我已经把出故障的页面图片转移到了掘金, 问题已解决, 感谢提醒!
