### ISSUE TITLE
项目有点乱，需要帮忙整理吗？

### ISSUE THREAD

**Issue by xinyu198736** [zhaoolee/ChromeAppHeroes#17]
看起来和维护起来有点乱

**Comment by zhaoolee** [comment]
- 这个项目创建于Gitbook, 所以文件命名出现了很多拼音
- 我也想整理一下, 但没有好的整理思路(由于项目已经做过一些宣传, 所以我想保留已有的文章超链接)
- 如果您有好的整理思路, 可以告知我~

芋头 <notifications@github.com> 于2019年5月7日周二 上午9:21写道：

**Comment by xinyu198736** [comment]
- 首页内容过多
- 内容结构较乱
- 具体文档最好能够收到文件夹里去
- 没找到贡献流程

**Comment by zhaoolee** [comment]
- 首页内容过多: 首页内容已完成整理,把核心内容前移, 次要内容后移, 不太相关的内容, 只在首页留了超链接
- 内容结构较乱: 已经对部分内容进行了删减
- 具体文档最好能够收到文件夹里去: 具体文档感觉放在最外层也没什么不好, 只有一级目录, 这样进入项目主页, 可以直接点击查看
- 贡献流程: 前期为了让内容保持比较高的质量, 我会读取issues的留言, 主动将优秀的插件(扩展程序)及使用技巧收录到项目中
