### ISSUE TITLE
推荐一个好用的划词翻译扩展 TransIt

### ISSUE THREAD

**Issue by today** [zhaoolee/ChromeAppHeroes#2]
安装地址：  https://chrome.google.com/webstore/detail/transit/pfjipfdmbpbkcadkdpmacdcefoohagdc?utm_source=chrome-ntp-icon

**Comment by zhaoolee** [comment]
嗯嗯,感谢推荐分享,下次我会把TransIt和谷歌翻译, 放到一起推送一篇 :-D
