### ISSUE TITLE
开发者模式运行插件建议停用

### ISSUE THREAD

**Issue by cat2mao** [zhaoolee/ChromeAppHeroes#23]
每次打开谷歌浏览器都会有提示开发者模式运行插件建议停用，有什么好的解决办法吗？网上的基本都不管用了

**Comment by zhaoolee** [comment]
直接从Chrome官方商店下载相关插件就好了，如果无法进入Chrome官方商店，可以先按照Chrome插件英雄榜 第44篇的内容，安装谷歌访问助手，安装完成后，就可以从官方自由下载插件了
