### ISSUE TITLE
推荐插件 Google Results Previewer

### ISSUE THREAD

**Issue by lIIllIIl** [zhaoolee/ChromeAppHeroes#28]
你好, zhaoo, 很感谢你对这个仓库的贡献, 它帮了我很多, 我刚才阅读完 Chrome 插件英雄榜的所有文章, 准确的说, 是第二次全文阅读了, 😁😁😁, 在查找安装时发现最喜欢的插件: Google 搜索结果预览这款没有在这个仓库中, 所以特别想推荐一下

官网: https://resultspreviewer.com/
Chrome Web Store: https://chrome.google.com/webstore/detail/google-results-previewer/mkmjdljkedjpedbceoaaghdmcnipdcjf

**Comment by zhaoolee** [comment]
感谢贡献, 完成收录了~ https://zhaoolee.gitbooks.io/chrome/content/050google-results-previewer.html
