### ISSUE TITLE
请问是否允许收录您的文章或URL链接等内容到我的极简插件网站里

### ISSUE THREAD

**Issue by 18121259693** [zhaoolee/ChromeAppHeroes#31]
一个不争气的小站 极简插件：https://chrome.zzzmh.cn 

我打算把您推荐过的除了我已收录的以外，大约45个扩展插件，一口气收录掉

就是不知道您这边是否介意我在插件详情页面直接引用您的文章中的简介
以及直接引用您的网站的内容转载过去，或者是引用您的网站的插件介绍的URL链接去到我那边的插件详情页。
总之刚才发了邮件，但是又很激动的跑到这里来发issues

有兴趣 方便的话可以详聊

admin@zzzmh.cn

**Comment by zhaoolee** [comment]
可以的，底部留个本仓库的开源地址就好了

https://github.com/zhaoolee/ChromeAppHeroes

**Comment by VPoplar** [comment]
可以



---原始邮件---
发件人: "zhaoolee"<notifications@github.com&gt;
发送时间: 2019年9月9日(星期一) 晚上6:30
收件人: "zhaoolee/ChromeAppHeroes"<ChromeAppHeroes@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [zhaoolee/ChromeAppHeroes] 请问是否允许收录您的文章或URL链接等内容到我的极简插件网站里 (#31)



Closed #31.
