### ISSUE TITLE
chrono插件下载地址404

### ISSUE THREAD

**Issue by hsessay** [zhaoolee/ChromeAppHeroes#32]
有不有非官网地址啊

**Comment by imjonat** [comment]
chrono被官方下架了，我找了一个月。。没找到

**Comment by zhaoolee** [comment]
chrono 历史版本下载地址 http://crx.dam.io/ext/mciiogijehkdemklbdcbfkefimifhecn.html

**Comment by imjonat** [comment]
> chrono 历史版本下载地址 http://crx.dam.io/ext/mciiogijehkdemklbdcbfkefimifhecn.html
> 
> ![image](https://user-images.githubusercontent.com/15868458/64513936-38fa8d00-d31c-11e9-85ad-04e96b3f0654.png)

thanks a lot, this is what i need.. XD
