### ISSUE TITLE
已经无法找到whatruns插件

### ISSUE THREAD

**Issue by fandean** [zhaoolee/ChromeAppHeroes#39]
whatruns插件已下架：
- 不管是通过点击 [011 《whatruns》一键分析网站技术栈 - V2方圆](https://www.v2fy.com/p/011_whatruns/) 文中的链接
- 还是直接在Chrome网上应用商店搜索 `whatruns` 

都找不到  whatruns

**Comment by zhaoolee** [comment]
海外用户: 在项目根目录文件夹[backup](https://github.com/zhaoolee/ChromeAppHeroes/tree/master/backup) 内可以找到ChromeAppHeroes所有离线安装包

国内用户: 在公众号 `0加1` 后台回复 `ChromeAppHeroes离线安装包` 即可获取
