### ISSUE TITLE
嗨,您好，我也在做相同的事喲

### ISSUE THREAD

**Issue by eric999j** [zhaoolee/ChromeAppHeroes#4]
https://github.com/eric999j/Clutter/blob/master/1.6.%E5%B7%A5%E7%A8%8B-%E5%A5%BD%E7%94%A8%E7%9A%84chrome%E6%8F%92%E4%BB%B6.md  
希望您看到有用的可以拿去補充

**Comment by zhaoolee** [comment]
好的，感谢！
