### ISSUE TITLE
插件自荐：浮图秀——持续改进的看大图神器。

### ISSUE THREAD

**Issue by Mr-VincentW** [zhaoolee/ChromeAppHeroes#40]
鼠标移过缩略图即可看高分辨率大图的浏览器插件有很多，多方比较还是觉得自己的这款最好用——操作简单，对 Facebook 及一票常用国内网站的支持更好，配合快捷键功能更强！

开源仓库地址：https://github.com/Mr-VincentW/PhotoShow

谢谢~

**Comment by zhaoolee** [comment]
已收录
