### ISSUE TITLE
很荣幸我的扩展也上榜了，但有个小问题

### ISSUE THREAD

**Issue by Kenshin** [zhaoolee/ChromeAppHeroes#7]
RT，上榜的是 简悦，但是在描述的时候有个错误。

***

> 029 《SimRead》为任意网页开启阅读模式

改为

> 029 《SimpRead》为任意网页开启阅读模式

***

即：SimRead → SimpRead （或称呼 `简悦` 也可）

***

另，也推荐下自己的另外两款扩展：

- 简 Tab → 可以改善心情的新标签页扩展，[地址](http://ksria.com/simptab)
- +Emoji → 简单、可靠、纯粹、中文语义化的 Emoji 扩展，[地址](http://ksria.com/emoji)

***

昨天发现的这个项目，并在 https://twitter.com/wanglei001/status/1115214341488304128 转了下，尽点自己的微小力量。

**Comment by zhaoolee** [comment]
哈哈, 已更正,感谢!
