### ISSUE TITLE
嗨，对我的 HitUP 感兴趣吗？

### ISSUE THREAD

**Issue by wonderbeyond** [zhaoolee/ChromeAppHeroes#9]
[HitUP](https://chrome.google.com/webstore/detail/hitup/eiokaohkigpbonodjcbjpecbnccijkjb) 是一款 Chrome 扩展，利用 New Tab “空白页” 助您保持对流行技术趋势的跟进，附带其它福利。

* 安装地址：https://chrome.google.com/webstore/detail/hitup/eiokaohkigpbonodjcbjpecbnccijkjb
* 仓库地址：https://github.com/wonderbeyond/HitUP
* 中文介绍&推广帖：https://www.v2ex.com/t/537982

主要特性：

* 展示 GitHub 项目趋势榜
* 随机展示一句话技巧（技术相关，来自我精心整理）

---

另外，HitUP 已经被 [《中国独立开发者项目列表》](https://github.com/1c7/chinese-independent-developer) 收录。

**Comment by zhaoolee** [comment]
嗯嗯, 我近期会在本项目新增一个 作者推荐插件的模块, 把您的插件收录进去, 感谢您的贡献!

**Comment by zhaoolee** [comment]
## 已收录到README主页
> ![](https://upload-images.jianshu.io/upload_images/3203841-60ce23837a70baaa.png)
